export const nexFinalHero = {
  title: "NEX",
  subtitle: "The Economic Layer of a Global Prediction Growth Infrastructure",
  sourceTitle: "NEX: The Economic Architecture of Global Prediction Growth Infrastructure",
};

export const strategicThesis = {
  title: "The Strategic Thesis: From Information to Intelligence Coordination",
  body:
    'The advancement of human civilization has reached a critical threshold. While the internet solved the movement of information and blockchain solved the movement of value, the "next great coordination problem" is the scaling of collective intelligence. We no longer suffer from a scarcity of information; we suffer from a systemic inability to coordinate foresight. NEX addresses this by providing the formal economic architecture for prediction networks, shifting the paradigm from speculative guessing to a productive infrastructure. This transition represents a fundamental structural change in how civilization allocates resources, moving away from fragmented information economies toward unified prediction economies where foresight is a primary productive force.',
};

export const predictionInfrastructure = {
  title: "Prediction as Infrastructure",
  introduction:
    'The evolution of prediction from a "forecasting activity" to "infrastructure" marks a civilizational shift in capital flow and technological emergence.',
  items: [
    {
      title: "Anchor Capital Allocation",
      body: "Prediction is no longer a guess; it is a service that reduces uncertainty, determining where global investment must flow to achieve optimal outcomes.",
    },
    {
      title: "Synchronize Technological Emergence",
      body: "Collective foresight acts as a filter, identifying viable technological trajectories and accelerating their path to market by reducing the cost of exploration.",
    },
    {
      title: "Generate Economic Gravity",
      body: "As prediction becomes reliable infrastructure, it creates an inescapable pull for developers and capital, moving the network from a choice to a necessity.",
    },
  ],
  close:
    "This shift necessitates a formal monetary framework—a coordination currency—to manage the transmission of these intelligence signals across the global economy.",
};

export const monetaryFramework = {
  title: "The NEX Monetary Framework: A Coordination Currency",
  body:
    'NEX is strategically architected as a "coordination asset," not a speculative instrument. In the emerging intelligence economy, Future Intelligence is the terminal resource. Coordinating this resource requires a native medium that transcends traditional scarcity models. NEX provides the shared economic language necessary to synchronize the incentives of human creators, communities, and AI agents, ensuring they act as a singular, cohesive intelligence unit.',
  evolution: [
    {
      title: "Store of Value",
      body: "Preserving the long-term economic relevance generated by predictive insights.",
    },
    {
      title: "Medium of Exchange",
      body: "Facilitating high-velocity interaction and value transmission within the foresight marketplace.",
    },
    {
      title: "Unit of Coordination",
      body: "Directing collective behavior across decentralized populations to ensure network adaptation and survival.",
    },
  ],
  predictionStandard:
    "We are moving toward a new monetary standard. Unlike the physical standards of the industrial age or the digital/scarcity standards of the early blockchain era, NEX establishes the Prediction Standard. This is a coordination-based standard where the value of the currency is derived from its ability to reduce uncertainty and synchronize global action.",
};

export const predictionValueChain = {
  title: "The Prediction Value Chain",
  introduction:
    "NEX facilitates the transition from raw expectation to global economic value through a distinct chain of intelligence:",
  steps: ["Prediction", "Signal", "Insight", "Influence", "Action", "Growth", "Economic Value"],
  transitions: [
    {
      title: "Prediction to Signal",
      body: "Individual expectations are synthesized into measurable, data-driven signals that reduce systemic uncertainty.",
    },
    {
      title: "Signal to Insight",
      body: "The network aggregates signals into intelligence, providing the clarity required for complex decision-making.",
    },
    {
      title: "Insight to Influence",
      body: "High-fidelity intelligence begins to guide the capital and resource allocation strategies of external actors.",
    },
    {
      title: "Influence to Action",
      body: "Decision-makers deploy resources based on network signals, transforming foresight into tangible reality.",
    },
    {
      title: "Action to Growth",
      body: "Effective coordination leads to ecosystem expansion, which the network captures as increased utility.",
    },
  ],
  close: "For this monetary layer to be sustainable, it must be anchored in a framework where the value generated by the network is successfully retained.",
};

export const valueAccrualFramework = {
  title: "Value Accrual Framework: The Economics of Signals and Gravity",
  body:
    'Traditional Web2 networks suffer from a "Value Capture Problem"—they create immense utility but fragment the rewards, often extracting value from the very participants who generate it. NEX reverses this by establishing a system where Value Creation > Value Capture. By ensuring the network generates more utility than it extracts, NEX secures long-term sustainability and participant alignment.',
  flywheelTitle: "The NEX Flywheel and Intelligence Compounding",
  flywheel:
    'The NEX economy functions as a self-reinforcing engine of "Economic Gravity." This is a compounding system where intelligence creates a competitive advantage that is impossible to ignore:',
  stages: [
    {
      title: "Participation",
      body: "Diverse inputs generate a high volume of raw data.",
    },
    {
      title: "Signal Generation",
      body: "Volume refines data into high-fidelity signals.",
    },
    {
      title: "Intelligence Compounding",
      body: "Superior signals aggregate into an intelligence advantage that improves with every cycle.",
    },
    {
      title: "Inescapable Adoption",
      body: "As predictive accuracy increases, it becomes infrastructure, forcing capital and developers to migrate to the network to remain competitive.",
    },
  ],
  close:
    "Capturing this value requires more than passive ownership; it demands a collective intelligence mechanism to steward that value effectively.",
};

export const governanceFramework = {
  title: "Governance as Collective Intelligence Coordination",
  body:
    'Governance is not "voting"; it is the "coordination of intelligence." In a decentralized prediction economy, governance is the process by which the network learns, adapts, and evolves to outcompete centralized alternatives.',
  pyramidTitle: "The Governance Pyramid",
  pyramidIntro: "The following hierarchy dictates the institutional imperatives for NEX participants:",
  pyramid: [
    {
      title: "Evolution",
      body: "Continuously adapt the ecosystem to capitalize on emerging technologies and market shifts.",
    },
    {
      title: "Governance",
      body: "Shape the strategic path by aligning collective intent with long-term network survival.",
    },
    {
      title: "Coordination",
      body: "Lead initiatives through working groups to execute the strategic vision of the network.",
    },
    {
      title: "Contribution",
      body: "Provide value as a developer or researcher to enhance the network's productive capacity.",
    },
    {
      title: "Participation",
      body: "Generate signals through active engagement, fueling the core intelligence engine.",
    },
  ],
  principles: [
    {
      title: "Progressive Decentralization",
      body: "This is a process, not an event. Governance evolves from concentrated coordination toward broad, effective decentralization as the network matures.",
    },
    {
      title: "Evolution Engine",
      body: 'This principle mandates that governance be used as a tool for experimentation, preventing stagnation and ensuring the network remains a "learning organism."',
    },
  ],
};

export const treasuryFramework = {
  title: "Treasury Framework and Network Constitution",
  body:
    "The NEX Treasury is the “Stewardship Layer,” a strategic reserve designed for generational growth rather than short-term cycles. It preserves the network’s optionality and resilience across decades.",
};

export const constitutionPrinciples = [
  {
    title: "Purpose-Driven Coordination",
    body: "To transform collective foresight into global action.",
  },
  {
    title: "Open Participation",
    body: "To ensure resilience through a diverse and decentralized contributor base.",
  },
  {
    title: "Prioritization of Collective Intelligence",
    body: "To outperform centralized decision-making models via aggregation.",
  },
  {
    title: "Long-Term Alignment",
    body: "Short-term incentives must not undermine long-term sustainability.",
  },
  {
    title: "Operational Transparency",
    body: "To foster the trust required for large-scale economic coordination.",
  },
  {
    title: "Responsible, Value-Based Growth",
    body: "To ensure expansion never compromises the integrity of the network.",
  },
  {
    title: "Continuous Innovation",
    body: "To ensure the network remains the dominant infrastructure in a changing landscape.",
  },
  {
    title: "Participant Stewardship",
    body: "To foster a culture of responsibility rather than mere speculative ownership.",
  },
  {
    title: "Effective Decentralization",
    body: "To evolve governance in lockstep with network maturity and complexity.",
  },
  {
    title: "Capability for Evolution",
    body: "To provide continuity while allowing for necessary, radical adaptation.",
  },
];

export const finalVision =
  "NEX is the foundational economic and organizational layer for the emerging intelligence economy. By aligning participation, capturing value through network relevance, and coordinating intelligence through a structured governance and treasury framework, NEX provides the essential infrastructure for the future of human and artificial cooperation.";
